apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-region2
  labels:
    app: frontend-region2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-region2
  template:
    metadata:
      labels:
        app: frontend-region2
    spec:
      containers:
        - name: frontend
          image: frontend-image-placeholder
          ports:
            - containerPort: 8080
