apiVersion: v1
kind: Service
metadata:
  name: frontend-region2
  labels:
    app: frontend-region2
spec:
  selector:
    app: frontend-region2
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30222
  type: NodePort
