apiVersion: v1
kind: Service
metadata:
  name: frontend-region
  labels:
    app: frontend-region
spec:
  selector:
    app: frontend-region
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
